[package]
name = "prompt-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.200", features = ["derive"] }
toml = "0.8.12"
predicates = "3.1.0"
chrono = "0.4.38"
no-comment = "0.0.3"